async function generatePayslipPDF(empId){
  await ensurePdfLibsLoaded();
  const c = state.clients[state.activeClient];
  const emp = c.employees.find(e => e.id === empId);
  const r = calcEmployee(emp);
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit:'pt', format: [297.64, 841.89] }); // A4 height kept as-is; width halved, per instruction
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const left = 32; const right = pageWidth - 32; let y = 40;
  const [br, bg, bb] = hexToRgb(c.brandColor || '#123C36');

  const line = (label, value, opts={}) => {
    doc.setFont('helvetica', opts.bold ? 'bold' : 'normal');
    doc.setFontSize(opts.size || 9.5);
    doc.text(label, left, y);
    doc.text(String(value), right, y, { align:'right' });
    y += opts.gap || 14;
  };
  const section = (title) => {
    y += 5;
    doc.setDrawColor(180); doc.line(left, y, right, y); y += 15;
    doc.setFont('helvetica','bold'); doc.setFontSize(10);
    doc.setTextColor(br, bg, bb);
    doc.text(title.toUpperCase(), left, y);
    doc.setTextColor(20,20,20);
    y += 15;
  };
  const centerX = pageWidth / 2;

  // Header block: logo, company name, "PAYSLIP" title, pay period - all centered.
  y += 6;
  if(c.logoDataUrl){
    try{
      const logoW = Math.min(c.logoSize || 60, 70);
      const logoH = logoW * (c.logoAspect || 0.75);
      doc.addImage(c.logoDataUrl, 'PNG', centerX - logoW / 2, y, logoW, logoH);
      y += logoH + 10;
    }catch(e){ /* ignore malformed image, don't block payslip generation */ }
  }

  doc.setFont('helvetica','bold'); doc.setFontSize(15);
  doc.setTextColor(br, bg, bb);
  doc.text(c.name || 'Payslip', centerX, y, { align:'center' });
  y += 17;

  doc.setFont('helvetica','bold'); doc.setFontSize(11);
  doc.setTextColor(20,20,20);
  doc.text('PAYSLIP', centerX, y, { align:'center' });
  y += 13;

  doc.setFont('helvetica','normal'); doc.setFontSize(9.5);
  doc.setTextColor(90,90,90);
  doc.text(`Pay Period: ${c.period || '-'}`, centerX, y, { align:'center' });
  doc.setTextColor(20,20,20);
  y += 16;

  // Bold rule, then a dotted rule beneath it, closing out the header block.
  doc.setLineWidth(1.4); doc.setDrawColor(20,20,20);
  doc.line(left, y, right, y);
  y += 5;
  doc.setLineWidth(0.75); doc.setLineDashPattern([1.5, 1.5], 0);
  doc.line(left, y, right, y);
  doc.setLineDashPattern([], 0); doc.setLineWidth(1);
  y += 16;

  // Remaining identifying fields, left-aligned as before.
  line('Employer PIN', c.kraPin || '-');
  line('Employee Name', emp.name || 'Unnamed');
  line('Payroll Number', emp.payrollNumber || '-');
  line('KRA PIN', emp.pin || '-');
  y += 4;

  section('Earnings');
  line('Basic salary', fmt(emp.basic));
  line('Allowances', fmt(emp.allowances));
  if(emp.overtimePay) line('Overtime pay', fmt(emp.overtimePay));
  (emp.bonusItems||[]).forEach(b => {
    if(b.amount) line(b.description ? `${b.type}: ${b.description}` : b.type, fmt(b.amount));
  });
  line('Gross pay', fmt(r.gross), { bold:true });

  section('Statutory deductions');
  line('NSSF (Tier I + II)', fmt(r.nssfEmployee));
  line('SHIF (2.75%)', fmt(r.shif));
  line('Housing Levy (1.5%)', fmt(r.ahlEmployee));
  if(r.voluntaryPension) line('Voluntary pension', fmt(r.voluntaryPension));
  y += 4;
  line('Taxable pay', fmt(r.taxable));
  line('Tax on taxable pay', fmt(r.grossTax));
  line('Less: personal relief', `-${fmt(RATES.personalRelief)}`);
  if(r.insuranceRelief) line('Less: insurance relief', `-${fmt(r.insuranceRelief)}`);
  line('PAYE', fmt(r.paye), { bold:true });

  const hasOtherDeductions = (emp.deductionItems||[]).some(d => d.amount);
  if(hasOtherDeductions){
    section('Other deductions');
    (emp.deductionItems||[]).forEach(d => {
      if(d.amount) line(d.description ? `${d.type}: ${d.description}` : d.type, fmt(d.amount));
    });
    line('Total other deductions', fmt(r.otherDeduct), { bold:true });
  }

  section('Net pay');
  doc.setFont('helvetica','bold'); doc.setFontSize(13);
  doc.setTextColor(br, bg, bb);
  doc.text('Take-home pay', left, y);
  doc.text(`KES ${fmt(r.net)}`, right, y, { align:'right' });
  doc.setTextColor(20,20,20);
  y += 26;

  doc.setFont('helvetica','italic'); doc.setFontSize(7.5); doc.setTextColor(140,140,140);
  doc.text('Generated by Edhafu Payroll. Verify statutory figures against current KRA/NSSF/SHA rates.', left, pageHeight - 24, { maxWidth: pageWidth - left * 2 });

  return { doc, filename: `${(emp.name||'employee').replace(/\s+/g,'_')}_payslip_${c.period||''}.pdf` };
}

async function downloadPayslipPDF(empId){
  const c = state.clients[state.activeClient];
  if(!requireAccess(c)) return;
  const { doc, filename } = await generatePayslipPDF(empId);
  doc.save(filename);
}

async function emailPayslip(empId, evt){
  const c = state.clients[state.activeClient];
  if(!requireAccess(c)) return;
  const emp = c.employees.find(e => e.id === empId);
  if(!emp.email){
    const addr = prompt('Enter this employee\'s email address:');
    if(!addr) return;
    await updateEmployeeField(empId, 'email', addr);
    emp.email = addr;
  }
  const { doc } = await generatePayslipPDF(empId);
  const pdfBase64 = doc.output('datauristring').split(',')[1];
  const btn = evt.target;
  const originalText = btn.textContent;
  btn.textContent = 'Sending...'; btn.disabled = true;
  try{
    const { data, error } = await sb.functions.invoke('send-payslip', {
      body: {
        to: emp.email,
        employeeName: emp.name,
        companyName: c.name,
        period: c.period,
        pdfBase64
      }
    });
    if(error) throw error;
    alert(`Payslip sent to ${emp.email}`);
  } catch(err){
    let detail = err.message || 'the email function may not be set up yet.';
    try{
      if(err.context && typeof err.context.json === 'function'){
        const body = await err.context.json();
        if(body && body.error) detail = body.error;
      }
    }catch(_){}
    alert('Could not send email: ' + detail);
  } finally {
    btn.textContent = originalText; btn.disabled = false;
  }
}

function toggleSettings(){
  openPanel(renderSettings());
}
function openPanel(html){
  document.getElementById('panelContent').innerHTML = html;
  document.getElementById('panelDrawer').classList.add('open');
  document.getElementById('panelBackdrop').classList.add('open');
}
function closePanel(){
  document.getElementById('panelDrawer').classList.remove('open');
  document.getElementById('panelBackdrop').classList.remove('open');
}
async function toggleActivityLog(){
  const c = state.clients[state.activeClient];
  if(!c) return;
  await ensureAuditLogLoaded(state.activeClient);
  openPanel(renderActivityLog(c));
}

/* ---------------- Multi-user company sharing ----------------
   Frontend hides/shows the panel for convenience only — the real security is the RLS
   policies in migration_012 (has_company_access). Even if this panel were shown to someone
   who shouldn't manage sharing, the database itself would reject their insert/delete.
------------------------------------------------------------------------------------- */
let shareListCache = {}; // companyId -> array of { id, email }
async function toggleSharePanel(){
  const c = state.clients[state.activeClient];
  if(!c || !state.activeClient) return;
  await loadShares(state.activeClient);
  openPanel(renderSharePanel(c));
}
async function loadShares(companyId){
  const { data, error } = await sb.from('company_access').select('*').eq('company_id', companyId);
  if(error){ console.error(error); shareListCache[companyId] = []; return; }
  shareListCache[companyId] = (data||[]).map(r => ({ id: r.id, email: r.granted_email, userId: r.user_id }));
}
async function shareCompanyWithColleague(){
  const email = prompt('Enter the email of a colleague who already has an account — they\'ll get full access to this client:');
  if(!email) return;
  const cleanEmail = email.trim().toLowerCase();
  const { data: foundId, error: lookupError } = await sb.rpc('get_user_id_by_email', { lookup_email: cleanEmail });
  if(lookupError){ alert('Could not look up that email: ' + lookupError.message); return; }
  if(!foundId){ alert(`No account found for ${cleanEmail}. Ask your colleague to sign up first (using the same sign-in screen), then try sharing again.`); return; }
  const { data: userData } = await sb.auth.getUser();
  const { error } = await sb.from('company_access').insert({
    company_id: state.activeClient, user_id: foundId, granted_email: cleanEmail, granted_by: userData?.user?.id
  });
  if(error){ alert('Could not share: ' + error.message); return; }
  logAudit('Client shared', `Access granted to ${cleanEmail}`);
  await loadShares(state.activeClient);
  openPanel(renderSharePanel(state.clients[state.activeClient]));
}
async function revokeShare(accessId, email){
  if(!confirm(`Remove ${email}'s access to this client?`)) return;
  const { error } = await sb.from('company_access').delete().eq('id', accessId);
  if(error){ alert('Could not revoke access: ' + error.message); return; }
  logAudit('Client access revoked', `Removed access for ${email}`);
  await loadShares(state.activeClient);
  openPanel(renderSharePanel(state.clients[state.activeClient]));
}
function renderSharePanel(c){
  const shares = shareListCache[state.activeClient] || [];
  const isOwner = c.ownerId === state.currentUserId;
  return `
    <div class="settings-panel">
      <h3 style="font-size:13px;color:var(--gold);font-family:'Inter',sans-serif;font-weight:600;margin-bottom:4px;">Share &amp; access — ${esc(c.name) || 'this client'}</h3>
      <div style="font-size:11.5px;color:var(--muted);margin-bottom:14px;">${isOwner ? 'People with access to this client (full access, same as yours).' : 'You have shared access to this client. Only the owner can manage who else has access.'}</div>
      ${shares.length === 0 ? `<div style="color:var(--muted);font-size:12.5px;padding:6px 0;">Not shared with anyone yet.</div>` : ''}
      ${shares.map(s => `
        <div style="display:flex;justify-content:space-between;align-items:center;padding:7px 0;border-bottom:1px solid var(--line);font-size:12.5px;">
          <span>${esc(s.email)}</span>
          ${isOwner ? `<span style="color:#EF4444;cursor:pointer;font-size:11.5px;" onclick="revokeShare('${s.id}', '${esc(s.email)}')">Remove</span>` : ''}
        </div>
      `).join('')}
      ${isOwner ? `<button class="btn primary" style="margin-top:14px;" onclick="shareCompanyWithColleague()">+ Share with a colleague</button>` : ''}
    </div>
  `;
}
function renderActivityLog(c){
  const entries = c.auditLog || [];
  return `
    <div class="settings-panel">
      <h3 style="font-size:13px;color:var(--gold);font-family:'Inter',sans-serif;font-weight:600;margin-bottom:4px;">Activity log — ${esc(c.name) || 'this client'}</h3>
      <div style="font-size:11.5px;color:var(--muted);margin-bottom:14px;">Most recent 50 actions. Who did what, and when.</div>
      ${entries.length === 0 ? `<div style="color:var(--muted);font-size:12.5px;padding:10px 0;">No activity recorded yet — actions like adding employees, salary changes, and finalizing payroll will appear here.</div>` : ''}
      <div style="max-height:340px;overflow-y:auto;">
        ${entries.map(a => `
          <div style="padding:8px 0;border-bottom:1px solid var(--line);font-size:12.5px;">
            <div style="display:flex;justify-content:space-between;gap:10px;">
              <span style="font-weight:600;color:var(--ink);">${esc(a.action)}</span>
              <span style="color:var(--muted);white-space:nowrap;font-family:'JetBrains Mono',monospace;font-size:11px;">${new Date(a.createdAt).toLocaleString('en-KE')}</span>
            </div>
            ${a.details ? `<div style="color:var(--muted);margin-top:2px;">${esc(a.details)}</div>` : ''}
            <div style="color:var(--muted);margin-top:2px;font-size:11px;">${esc(a.userEmail)}</div>
          </div>
        `).join('')}
      </div>
    </div>
  `;
}
function openDrawer(empId){
  const c = state.clients[state.activeClient];
  const emp = c.employees.find(e => e.id === empId);
  const r = calcEmployee(emp);
  document.getElementById('drawerContent').innerHTML = `
    <h2>${esc(emp.name) || 'Unnamed employee'}</h2>
    <div class="role">${esc(c.name) || 'Client'} &middot; ${esc(c.period) || 'Pay period not set'}</div>

    <div class="payslip-section">
      <h3>Statutory identifiers</h3>
      <div class="settings-grid" style="grid-template-columns:1fr 1fr;">
        <div class="settings-field"><label>KRA PIN</label><input value="${esc(emp.pin)}" onchange="updateEmployeeField('${emp.id}','pin',this.value); openDrawer('${emp.id}')"/></div>
        <div class="settings-field"><label>National ID</label><input value="${esc(emp.idNumber)}" onchange="updateEmployeeField('${emp.id}','idNumber',this.value); openDrawer('${emp.id}')"/></div>
        <div class="settings-field"><label>NSSF number</label><input value="${esc(emp.nssfNo)}" onchange="updateEmployeeField('${emp.id}','nssfNo',this.value); openDrawer('${emp.id}')"/></div>
        <div class="settings-field"><label>SHA number</label><input value="${esc(emp.shaNo)}" onchange="updateEmployeeField('${emp.id}','shaNo',this.value); openDrawer('${emp.id}')"/></div>
        <div class="settings-field"><label>Payroll number</label><input value="${esc(emp.payrollNumber)}" placeholder="e.g. EMP001" onchange="updateEmployeeField('${emp.id}','payrollNumber',this.value); openDrawer('${emp.id}')"/></div>
        <div class="settings-field"><label>Phone</label><input value="${esc(emp.phone)}" onchange="updateEmployeeField('${emp.id}','phone',this.value); openDrawer('${emp.id}')"/></div>
        <div class="settings-field" style="grid-column:1 / -1;"><label>Email (for payslip delivery)</label><input type="email" value="${esc(emp.email)}" placeholder="employee@example.com" onchange="updateEmployeeField('${emp.id}','email',this.value); openDrawer('${emp.id}')"/></div>
      </div>
    </div>

    <div class="payslip-section">
      <h3>Filing details</h3>
      <div class="settings-grid" style="grid-template-columns:1fr 1fr;">
        <div class="settings-field"><label>Department</label><input value="${esc(emp.department)}" placeholder="e.g. Finance" onchange="updateEmployeeField('${emp.id}','department',this.value); openDrawer('${emp.id}')"/></div>
        <div class="settings-field"><label>Annual leave entitlement (days)</label><input type="number" value="${emp.annualLeaveEntitlement ?? 21}" onchange="updateEmployeeField('${emp.id}','annualLeaveEntitlement',this.value); openDrawer('${emp.id}')"/></div>
        <div class="settings-field"><label>Employment status</label>
          <select onchange="updateEmployeeField('${emp.id}','employmentStatus',this.value); openDrawer('${emp.id}')" style="width:100%;background:var(--bg);border:1px solid var(--line);color:var(--ink);border-radius:4px;padding:6px 8px;font-size:12.5px;">
            <option ${emp.employmentStatus==='Active'?'selected':''}>Active</option>
            <option ${emp.employmentStatus==='On Leave'?'selected':''}>On Leave</option>
            <option ${emp.employmentStatus==='Terminated'?'selected':''}>Terminated</option>
          </select>
        </div>
        <div class="settings-field"><label>Residential status</label>
          <select onchange="updateEmployeeField('${emp.id}','residentialStatus',this.value); openDrawer('${emp.id}')" style="width:100%;background:var(--bg);border:1px solid var(--line);color:var(--ink);border-radius:4px;padding:6px 8px;font-size:12.5px;">
            <option ${emp.residentialStatus==='Resident'?'selected':''}>Resident</option>
            <option ${emp.residentialStatus==='Non-resident'?'selected':''}>Non-resident</option>
          </select>
        </div>
        <div class="settings-field"><label>Employee type</label>
          <select onchange="updateEmployeeField('${emp.id}','employeeType',this.value); openDrawer('${emp.id}')" style="width:100%;background:var(--bg);border:1px solid var(--line);color:var(--ink);border-radius:4px;padding:6px 8px;font-size:12.5px;">
            <option ${emp.employeeType==='Primary Employee'?'selected':''}>Primary Employee</option>
            <option ${emp.employeeType==='Secondary Employee'?'selected':''}>Secondary Employee</option>
          </select>
        </div>
        <div class="settings-field"><label>Disability</label>
          <select onchange="updateEmployeeField('${emp.id}','disability',this.value); openDrawer('${emp.id}')" style="width:100%;background:var(--bg);border:1px solid var(--line);color:var(--ink);border-radius:4px;padding:6px 8px;font-size:12.5px;">
            <option ${emp.disability==='No'?'selected':''}>No</option>
            <option ${emp.disability==='Yes'?'selected':''}>Yes</option>
          </select>
        </div>
        ${emp.disability==='Yes' ? `<div class="settings-field"><label>Exemption certificate no.</label><input value="${esc(emp.exemptionCertNo)}" onchange="updateEmployeeField('${emp.id}','exemptionCertNo',this.value); openDrawer('${emp.id}')"/></div>` : ''}
        <div class="settings-field"><label>ID type (SHA filing)</label>
          <select onchange="updateEmployeeField('${emp.id}','identityType',this.value); openDrawer('${emp.id}')" style="width:100%;background:var(--bg);border:1px solid var(--line);color:var(--ink);border-radius:4px;padding:6px 8px;font-size:12.5px;">
            <option ${emp.identityType==='National ID'?'selected':''}>National ID</option>
            <option ${emp.identityType==='Passport'?'selected':''}>Passport</option>
            <option ${emp.identityType==='Alien ID'?'selected':''}>Alien ID</option>
          </select>
        </div>
        <div class="settings-field"><label>Non-cash benefit (KES)</label><input type="number" value="${emp.benefitAmount||''}" placeholder="0" onchange="updateEmployeeField('${emp.id}','benefitAmount',this.value); openDrawer('${emp.id}')"/></div>
        <div class="settings-field" style="grid-column:1 / -1;"><label>Benefit description</label><input value="${esc(emp.benefitDescription)}" placeholder="Benefit not given" onchange="updateEmployeeField('${emp.id}','benefitDescription',this.value); openDrawer('${emp.id}')"/></div>
      </div>
    </div>

    <div class="payslip-section">
      <h3>Earnings</h3>
      <div class="payslip-line"><span>Basic salary</span><span>${fmt(emp.basic)}</span></div>
      <div class="payslip-line"><span>Allowances</span><span>${fmt(emp.allowances)}</span></div>
      ${emp.overtimePay ? `<div class="payslip-line"><span>Overtime pay</span><span>${fmt(emp.overtimePay)}</span></div>` : ''}
      <div class="payslip-line total"><span>Gross pay</span><span>${fmt(r.gross)}</span></div>
    </div>

    <div class="payslip-section">
      <h3>Statutory deductions</h3>
      <div class="payslip-line"><span>NSSF (Tier I + II)</span><span>${fmt(r.nssfEmployee)}</span></div>
      <div class="payslip-line"><span>SHIF (2.75%)</span><span>${fmt(r.shif)}</span></div>
      <div class="payslip-line"><span>Housing Levy (1.5%)</span><span>${fmt(r.ahlEmployee)}</span></div>
      ${r.voluntaryPension ? `<div class="payslip-line"><span>Voluntary pension</span><span>${fmt(r.voluntaryPension)}</span></div>` : ''}
      <div class="payslip-line"><span>Taxable pay</span><span>${fmt(r.taxable)}</span></div>
      <div class="payslip-line"><span>Tax on taxable pay</span><span>${fmt(r.grossTax)}</span></div>
      <div class="payslip-line"><span>Less: personal relief</span><span>-${fmt(RATES.personalRelief)}</span></div>
      ${r.insuranceRelief ? `<div class="payslip-line"><span>Less: insurance relief</span><span>-${fmt(r.insuranceRelief)}</span></div>` : ''}
      <div class="payslip-line total"><span>PAYE</span><span>${fmt(r.paye)}</span></div>
    </div>

    <div class="payslip-section">
      <h3>One-off pay <span style="font-weight:400;color:var(--muted);font-size:11px;">(bonus, commission — cleared automatically after this period is finalized, unless marked recurring)</span></h3>
      ${(emp.bonusItems||[]).length === 0 ? `<div style="font-size:12px;color:var(--muted);margin-bottom:8px;">None on file for this pay period.</div>` : ''}
      ${(emp.bonusItems||[]).map((d, idx) => `
        <div style="display:flex;gap:6px;align-items:center;margin-bottom:6px;">
          <select onchange="updateBonusItem('${emp.id}', ${idx}, 'type', this.value)" style="flex:1;background:var(--bg);border:1px solid var(--line);color:var(--ink);border-radius:4px;padding:6px 6px;font-size:12px;">
            ${BONUS_TYPES.map(t => `<option ${d.type===t?'selected':''}>${t}</option>`).join('')}
          </select>
          <input type="number" value="${d.amount||''}" placeholder="0" oninput="updateBonusItem('${emp.id}', ${idx}, 'amount', this.value)" style="width:75px;background:var(--bg);border:1px solid var(--line);color:var(--ink);border-radius:4px;padding:6px 8px;font-size:12px;font-family:'JetBrains Mono',monospace;"/>
          <input value="${esc(d.description)}" placeholder="Note (optional)" onchange="updateBonusItem('${emp.id}', ${idx}, 'description', this.value)" style="flex:1.2;background:var(--bg);border:1px solid var(--line);color:var(--ink);border-radius:4px;padding:6px 8px;font-size:12px;"/>
          <label style="display:flex;align-items:center;gap:3px;font-size:10.5px;color:var(--muted);white-space:nowrap;" title="If checked, this keeps appearing every period instead of being cleared after finalizing">
            <input type="checkbox" ${isRecurring(d)?'checked':''} onchange="updateBonusItem('${emp.id}', ${idx}, 'recurring', this.checked)" style="width:13px;height:13px;accent-color:var(--gold);" />Recurring
          </label>
          <span class="row-del" style="opacity:.6;" onclick="removeBonusItem('${emp.id}', ${idx})">&times;</span>
        </div>
      `).join('')}
      <button class="add-row-btn" style="padding:6px 2px;" onclick="addBonusItem('${emp.id}')">+ Add one-off pay</button>
      ${(emp.bonusItems||[]).length > 0 ? `<div class="payslip-line total" style="margin-top:8px;"><span>Total one-off pay</span><span id="drawerBonusTotal">${fmt(r.bonusPay)}</span></div>` : ''}
    </div>

    <div class="payslip-section">
      <h3>Other deductions</h3>
      ${(emp.deductionItems||[]).length === 0 ? `<div style="font-size:12px;color:var(--muted);margin-bottom:8px;">None on file for this pay period.</div>` : ''}
      ${(emp.deductionItems||[]).map((d, idx) => `
        <div style="display:flex;gap:6px;align-items:center;margin-bottom:6px;">
          <select onchange="updateDeductionItem('${emp.id}', ${idx}, 'type', this.value)" style="flex:1;background:var(--bg);border:1px solid var(--line);color:var(--ink);border-radius:4px;padding:6px 6px;font-size:12px;">
            ${DEDUCTION_TYPES.map(t => `<option ${d.type===t?'selected':''}>${t}</option>`).join('')}
          </select>
          <input type="number" value="${d.amount||''}" placeholder="0" oninput="updateDeductionItem('${emp.id}', ${idx}, 'amount', this.value)" style="width:75px;background:var(--bg);border:1px solid var(--line);color:var(--ink);border-radius:4px;padding:6px 8px;font-size:12px;font-family:'JetBrains Mono',monospace;"/>
          <input value="${esc(d.description)}" placeholder="Note (optional)" onchange="updateDeductionItem('${emp.id}', ${idx}, 'description', this.value)" style="flex:1.2;background:var(--bg);border:1px solid var(--line);color:var(--ink);border-radius:4px;padding:6px 8px;font-size:12px;"/>
          <label style="display:flex;align-items:center;gap:3px;font-size:10.5px;color:var(--muted);white-space:nowrap;" title="If unchecked, this is cleared automatically after finalizing this period">
            <input type="checkbox" ${isRecurring(d)?'checked':''} onchange="updateDeductionItem('${emp.id}', ${idx}, 'recurring', this.checked)" style="width:13px;height:13px;accent-color:var(--gold);" />Recurring
          </label>
          <span class="row-del" style="opacity:.6;" onclick="removeDeductionItem('${emp.id}', ${idx})">&times;</span>
        </div>
      `).join('')}
      <button class="add-row-btn" style="padding:6px 2px;" onclick="addDeductionItem('${emp.id}')">+ Add deduction</button>
      ${(emp.deductionItems||[]).length > 0 ? `<div class="payslip-line total" style="margin-top:8px;"><span>Total other deductions</span><span id="drawerOtherDeductTotal">${fmt(r.otherDeduct)}</span></div>` : ''}
    </div>

    <div class="payslip-section">
      <h3>Net pay</h3>
      <div class="payslip-line net total"><span>Take-home</span><span id="drawerNetPay">KES ${fmt(r.net)}</span></div>
    </div>

    <div class="payslip-section">
      <h3>Employer cost (not deducted from employee)</h3>
      <div class="payslip-line"><span>NSSF employer match</span><span>${fmt(r.nssfEmployer)}</span></div>
      <div class="payslip-line"><span>Housing Levy employer match</span><span>${fmt(r.ahlEmployer)}</span></div>
      <div class="payslip-line"><span>NITA levy</span><span>${fmt(r.nita)}</span></div>
      <div class="payslip-line total"><span>Total cost to employer</span><span>${fmt(r.employerCost)}</span></div>
    </div>

    <div class="actions" style="margin-bottom:0;">
      <button class="btn primary" style="flex:1;" onclick="downloadPayslipPDF('${emp.id}')">Download PDF</button>
      <button class="btn" style="flex:1;" onclick="emailPayslip('${emp.id}', event)">Email to employee</button>
    </div>
  `;
  document.getElementById('drawer').classList.add('open');
  document.getElementById('drawerBackdrop').classList.add('open');
}
function closeDrawer(){
  document.getElementById('drawer').classList.remove('open');
  document.getElementById('drawerBackdrop').classList.remove('open');
}
